/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracaoRouteImport } from './routes/configuracao'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ExpedicaoRouteImport } from './routes/expedicao'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as ModuloIdRouteImport } from './routes/modulo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoRoute = ConfiguracaoRouteImport.update({
  id: '/configuracao',
  path: '/configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicaoRoute = ExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloIdRoute = ModuloIdRouteImport.update({
  id: '/modulo/$id',
  path: '/modulo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/estoque': typeof EstoqueRoute
  '/expedicao': typeof ExpedicaoRoute
  '/indicadores': typeof IndicadoresRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/estoque': typeof EstoqueRoute
  '/expedicao': typeof ExpedicaoRoute
  '/indicadores': typeof IndicadoresRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/estoque': typeof EstoqueRoute
  '/expedicao': typeof ExpedicaoRoute
  '/indicadores': typeof IndicadoresRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracao'
    | '/estoque'
    | '/expedicao'
    | '/indicadores'
    | '/monitoramento'
    | '/modulo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracao'
    | '/estoque'
    | '/expedicao'
    | '/indicadores'
    | '/monitoramento'
    | '/modulo/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracao'
    | '/estoque'
    | '/expedicao'
    | '/indicadores'
    | '/monitoramento'
    | '/modulo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracaoRoute: typeof ConfiguracaoRoute
  EstoqueRoute: typeof EstoqueRoute
  ExpedicaoRoute: typeof ExpedicaoRoute
  IndicadoresRoute: typeof IndicadoresRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  ModuloIdRoute: typeof ModuloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao': {
      id: '/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof ConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicao': {
      id: '/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof ExpedicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$id': {
      id: '/modulo/$id'
      path: '/modulo/$id'
      fullPath: '/modulo/$id'
      preLoaderRoute: typeof ModuloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracaoRoute: ConfiguracaoRoute,
  EstoqueRoute: EstoqueRoute,
  ExpedicaoRoute: ExpedicaoRoute,
  IndicadoresRoute: IndicadoresRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  ModuloIdRoute: ModuloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
